version: "3.8"
services:
  my-app:
    build:
      context: .
      target: ${MY_ENV}
    image: my-next-app:${MY_ENV}
    ports:
      - "8000:${MY_PORT}"
    volumes:
      - ./pages:/app/src
    environment:
      PORT: ${MY_PORT}
