import type { NextPage } from 'next'
import Head from 'next/head'
import Show from '../comps/shows'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  let nxtTitles = ["NXT Men's Championship","NXT Women's Championship","North American Championship","NXT Men's Tag Team Championships","NXT Women's Tag Team Championships"]
  return (
    <div className={styles.container}>
      <Head>
        <title>Wrestling Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ring.svg" />
      </Head>
      <Show name={"WWE NXT"} titles={nxtTitles} rosterSize={2} />
    </div>
  )
}

export default Home
